# Generated by Django 3.2.12 on 2022-03-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='register_as',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profile_image',
            field=models.ImageField(default='image/Screenshot_from_2022-01-19_15-11-15.png', upload_to='image/'),
        ),
    ]
