# Generated by Django 3.2.12 on 2022-03-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userdetails_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
