# Generated by Django 3.2.12 on 2022-03-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.CharField(choices=[('React', 'React'), ('Python', 'Python'), ('Tech', 'Tech'), ('Java', 'Java')], default='Tech', max_length=100),
        ),
    ]
