# Generated by Django 3.2.12 on 2022-03-14 05:56

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_tags'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userdetails',
            managers=[
                ('doctors', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='proffession',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Developer', 'Developer'), ('Hr', 'Hr'), ('Manager', 'Manager')], default='Doctor', max_length=50),
        ),
    ]
